"""add warehouse receipts and factory voucher line description receiving qty

Revision ID: 0fae71bc2b91
Revises: 258d7e0f6aef
Create Date: 2026-08-29 18:55:00.302382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fae71bc2b91'
down_revision: Union[str, Sequence[str], None] = '258d7e0f6aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('voucher_line_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=255), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voucher_line_id'], ['factory_voucher_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('factory_voucher_lines', sa.Column('description', sa.String(length=500), nullable=True))
    # Existing rows have no receiving history yet — default them to 0 rather than leaving
    # NOT NULL unsatisfiable, then drop the server default so future inserts rely on the
    # ORM-level default instead.
    op.add_column(
        'factory_voucher_lines',
        sa.Column('received_qty', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    )
    op.alter_column('factory_voucher_lines', 'received_qty', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factory_voucher_lines', 'received_qty')
    op.drop_column('factory_voucher_lines', 'description')
    op.drop_table('warehouse_receipts')
    # ### end Alembic commands ###
