"""add products, sales, purchases, stock_levels tables

Revision ID: 3a3d25b877e3
Revises: 81393732eaaa
Create Date: 2026-08-23 01:06:24.234914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3d25b877e3'
down_revision: Union[str, Sequence[str], None] = '81393732eaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stock_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('location_raw', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('location_raw', sa.String(length=255), nullable=True),
    sa.Column('slip_id', sa.String(length=50), nullable=False),
    sa.Column('slip_number', sa.String(length=20), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_time', sa.String(length=20), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_id')
    )
    op.create_table('stock_levels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('location_raw', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('on_hand_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buying_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_levels_product_branch_snapshot', 'stock_levels', ['product_id', 'branch_id', 'snapshot_at'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=30), nullable=True),
    sa.Column('buying_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_lines_purchase_id', 'purchase_lines', ['purchase_id'], unique=False)
    op.create_table('sale_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=60), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=30), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id')
    )
    op.create_index('ix_sale_lines_sale_id', 'sale_lines', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_lines_sale_id', table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index('ix_purchase_lines_purchase_id', table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index('ix_stock_levels_product_branch_snapshot', table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_table('sales')
    op.drop_table('purchases')
    op.drop_table('products')
    # ### end Alembic commands ###
