"""scope sale_lines line_id uniqueness to sale

Revision ID: 3fe51cec6420
Revises: daba971f0bec
Create Date: 2026-08-30 16:39:24.581586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe51cec6420'
down_revision: Union[str, Sequence[str], None] = 'daba971f0bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sale_lines_line_id_key'), 'sale_lines', type_='unique')
    op.create_unique_constraint('uq_sale_lines_sale_id_line_id', 'sale_lines', ['sale_id', 'line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sale_lines_sale_id_line_id', 'sale_lines', type_='unique')
    op.create_unique_constraint(op.f('sale_lines_line_id_key'), 'sale_lines', ['line_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
