"""add import batch health dismissal

Revision ID: 617428f4df12
Revises: 3fe51cec6420
Create Date: 2026-08-30 17:52:41.530397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617428f4df12'
down_revision: Union[str, Sequence[str], None] = '3fe51cec6420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batches', sa.Column('health_dismissed_at', sa.DateTime(), nullable=True))
    op.add_column('import_batches', sa.Column('health_dismissed_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'import_batches', 'users', ['health_dismissed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_batches', type_='foreignkey')
    op.drop_column('import_batches', 'health_dismissed_by')
    op.drop_column('import_batches', 'health_dismissed_at')
    # ### end Alembic commands ###
