"""add preview_data to import_batches

Revision ID: 6a69cbde81e9
Revises: 78cfcd052df7
Create Date: 2026-08-23 14:11:57.705714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a69cbde81e9'
down_revision: Union[str, Sequence[str], None] = '78cfcd052df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'import_batches',
        sa.Column('preview_data', sa.JSON(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'preview_data')
    # ### end Alembic commands ###
