"""add branch/date and import_batch_id indexes

Revision ID: 6e551401153d
Revises: a69e3d42650e
Create Date: 2026-08-28 19:46:26.997235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e551401153d'
down_revision: Union[str, Sequence[str], None] = 'a69e3d42650e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_import_batches_branch_id_created_at', 'import_batches', ['branch_id', 'created_at'], unique=False)
    op.create_index('ix_purchases_branch_id_purchase_date', 'purchases', ['branch_id', 'purchase_date'], unique=False)
    op.create_index('ix_purchases_import_batch_id', 'purchases', ['import_batch_id'], unique=False)
    op.create_index('ix_sales_branch_id_sale_date', 'sales', ['branch_id', 'sale_date'], unique=False)
    op.create_index('ix_sales_import_batch_id', 'sales', ['import_batch_id'], unique=False)
    op.create_index('ix_stock_levels_branch_id_snapshot_at', 'stock_levels', ['branch_id', 'snapshot_at'], unique=False)
    op.create_index('ix_stock_levels_import_batch_id', 'stock_levels', ['import_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_levels_import_batch_id', table_name='stock_levels')
    op.drop_index('ix_stock_levels_branch_id_snapshot_at', table_name='stock_levels')
    op.drop_index('ix_sales_import_batch_id', table_name='sales')
    op.drop_index('ix_sales_branch_id_sale_date', table_name='sales')
    op.drop_index('ix_purchases_import_batch_id', table_name='purchases')
    op.drop_index('ix_purchases_branch_id_purchase_date', table_name='purchases')
    op.drop_index('ix_import_batches_branch_id_created_at', table_name='import_batches')
    # ### end Alembic commands ###
