"""add import_batches table and batch links

Revision ID: 78cfcd052df7
Revises: 3a3d25b877e3
Create Date: 2026-08-23 02:28:41.897159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cfcd052df7'
down_revision: Union[str, Sequence[str], None] = '3a3d25b877e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_type', sa.Enum('sales', 'inventory', 'purchase', name='importtype'), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('completed', 'reverted', name='importbatchstatus'), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.Column('reverted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['reverted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchases', sa.Column('import_batch_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'purchases', 'import_batches', ['import_batch_id'], ['id'])
    op.add_column('sales', sa.Column('import_batch_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'sales', 'import_batches', ['import_batch_id'], ['id'])
    op.add_column('stock_levels', sa.Column('import_batch_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'stock_levels', 'import_batches', ['import_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_levels', type_='foreignkey')
    op.drop_column('stock_levels', 'import_batch_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'import_batch_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'import_batch_id')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
