"""add customer_orders and factory_vouchers tables

Revision ID: 86d94eee9a44
Revises: 6a69cbde81e9
Create Date: 2026-08-25 14:59:01.669920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d94eee9a44'
down_revision: Union[str, Sequence[str], None] = '6a69cbde81e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('voucher_no', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('factory_name', sa.String(length=255), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('buying_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('discount_per_set', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('factory_name', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('first_commit_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('second_commit_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('total_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('buying_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('not_start', 'waiting', 'complete', name='orderstatus'), nullable=False),
    sa.Column('matched_voucher_id', sa.String(length=36), nullable=True),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['matched_voucher_id'], ['factory_vouchers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_orders')
    op.drop_table('factory_vouchers')
    # ### end Alembic commands ###
