"""scope sales slip_id uniqueness to branch

Revision ID: daba971f0bec
Revises: b1c9f3a72d44
Create Date: 2026-08-30 16:38:24.779072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daba971f0bec'
down_revision: Union[str, Sequence[str], None] = 'b1c9f3a72d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sales_slip_id_key'), 'sales', type_='unique')
    op.create_unique_constraint('uq_sales_branch_id_slip_id', 'sales', ['branch_id', 'slip_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sales_branch_id_slip_id', 'sales', type_='unique')
    op.create_unique_constraint(op.f('sales_slip_id_key'), 'sales', ['slip_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
